dist: trusty
sudo: required
language: cpp
compiler: clang

before_script:
- sudo apt-get update -qq

script:
  # Install Boost Test Framework 1.54
- sudo apt-get install -y -qq doxygen libboost-test1.54-dev
- cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- cat Doxyfile ; echo "PROJECT_NUMBER=0.0.${TRAVIS_BUILD_NUMBER} | doxygen
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: html
    on:
      branch: master
 # - provider: script
 #   skip_cleanup: true
 #   script:
 #   - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uithamsteri:$BINTRAY_API_KEY "https://api.bintray.com/content/hamsterisoft/apt-repo/print_ip/0.0.$TRAVIS_BUILD_NUMBER/pool/main/p/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1;override=1"