dist: trusty
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - doxygen
      - graphviz
      - libboost-test1.54-dev
      - cmake

script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
- cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: html
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uithamsteri:$BINTRAY_API_KEY "https://api.bintray.com/content/hamsterisoftware/deb-repo/print_ip/0.0.$TRAVIS_BUILD_NUMBER/pool/main/p/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1;override=1"
